{"uid":"9630dfe305177987","name":"test_xfail","fullName":"test.allure_status_test#test_xfail","historyId":"77aa3ee7069d023b0fd97f7c40d7d179","time":{"start":1696588260098,"stop":1696588260098,"duration":0},"status":"skipped","statusMessage":"XFAIL Some xfail reason\n\nAssertionError: Assertion failed\nassert False","statusTrace":"@pytest.mark.xfail(reason=\"Some xfail reason\")\n    def test_xfail():\n>       assert False, \"Assertion failed\"\nE       AssertionError: Assertion failed\nE       assert False\n\ntest/allure_status_test.py:24: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='Some xfail reason')"},{"name":"parentSuite","value":"test"},{"name":"suite","value":"allure_status_test"},{"name":"host","value":"fv-az955-5"},{"name":"thread","value":"2149-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.allure_status_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.xfail(reason='Some xfail reason')"]},"source":"9630dfe305177987.json","parameterValues":[]}