{
  "uid" : "a6d1ef9751b652b9",
  "name" : "test_failed",
  "fullName" : "test.allure_status_test#test_failed",
  "historyId" : "4da3226ec9761b158ba5f826fc8f8289",
  "time" : {
    "start" : 1620246647397,
    "stop" : 1620246647397,
    "duration" : 0
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: Some fail reason\nassert False",
  "statusTrace" : "def test_failed():\n>       assert False, \"Some fail reason\"\nE       AssertionError: Some fail reason\nE       assert False\n\ntest/allure_status_test.py:9: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "allure_status_test"
  }, {
    "name" : "host",
    "value" : "fv-az231-191"
  }, {
    "name" : "thread",
    "value" : "2873-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.allure_status_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "a6d1ef9751b652b9.json",
  "parameterValues" : [ ]
}